const fs = require('fs');
var text = fs.readFileSync('index.html', 'utf8');
// Remove all non-ASCII garbled sequences before known text
text = text.replace(/[^\x00-\x7E]+MCL Client Manager/g, '&#9878;&#65039; MCL Client Manager');
text = text.replace(/[^\x00-\x7E]+Sync Sheet/g, '&#128260; Sync Sheet');
text = text.replace(/[^\x00-\x7E]+Need to Call/g, '&#128222; Need to Call');
text = text.replace(/[^\x00-\x7E]+LVM/g, '&#128222; LVM');
text = text.replace(/[^\x00-\x7E]+Contacted/g, '&#128172; Contacted');
text = text.replace(/[^\x00-\x7E]+Waiting on MCL/g, '&#9203; Waiting on MCL');
text = text.replace(/[^\x00-\x7E]+Packet Sent/g, '&#128236; Packet Sent');
text = text.replace(/[^\x00-\x7E]+Disputes Mailed/g, '&#128238; Disputes Mailed');
text = text.replace(/[^\x00-\x7E]+Waiting on Reports/g, '&#128202; Waiting on Reports');
text = text.replace(/[^\x00-\x7E]+Litigation/g, '&#9878;&#65039; Litigation');
text = text.replace(/[^\x00-\x7E]+Won/g, '&#9989; Won');
text = text.replace(/[^\x00-\x7E]+Lost/g, '&#10060; Lost');
text = text.replace(/[^\x00-\x7E]+Send Email/g, '&#128231; Send Email');
text = text.replace(/[^\x00-\x7E]+Send Text/g, '&#128172; Send Text');
text = text.replace(/[^\x00-\x7E]+Send Both/g, '&#128231;&#128172; Send Both');
text = text.replace(/[^\x00-\x7E]+Delete/g, '&#128465; Delete');
text = text.replace(/[^\x00-\x7E]+ADD EMAIL/g, '&#9888; ADD EMAIL');
text = text.replace(/[^\x00-\x7E]+ADD PHONE/g, '&#9888; ADD PHONE');
text = text.replace(/[^\x00-\x7E]+Send Manual/g, '&#9993; Send Manual');
text = text.replace(/[^\x00-\x7E]+Activity History/g, '&#128220; Activity History');
text = text.replace(/[^\x00-\x7E]+Follow-up Timeline/g, '&#128203; Follow-up Timeline');
// Clean any remaining garbled sequences (standalone)
text = text.replace(/[^\x00-\x7E]{3,}/g, '');
fs.writeFileSync('index.html', text, 'utf8');
var t = fs.readFileSync('index.html','utf8');
console.log(t.includes('&#9878;') ? 'FIXED' : 'PROBLEM');
console.log(t.includes('sendManualEmail') ? 'COMPOSE:YES' : 'COMPOSE:NO');
